version: '3'

services:
   db:
     image: mysql:8.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}

   wordpress:
     image: wordpress:6.3.1-php8.0-fpm
     volumes:
       - ./wordpress:/var/www/html
       - ./docker/wordpress/php.ini:/usr/local/etc/php/php.ini
       - ./wp-jp-mep-themes/help/meviy_manual:/var/www/html/wp-content/themes/meviy_manual
     restart: always
     environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
     depends_on:
      - db
    
   nginx:
     image: nginx:stable
     ports:
      - '${NGINX_HOST_PORT}:80'
     volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
      - ./wordpress:/var/www/html
     restart: always
     depends_on:
      - wordpress

   phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - 8080:80
      restart: always
      depends_on:
        - db

volumes:
    db_data: